FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY bkk_collector ./bkk_collector
COPY public_exporter ./public_exporter
USER 65532:65532
CMD ["python", "-u", "-m", "public_exporter"]
